const actionTypes = {
  ADD_USER: "ADD_USER",
  USER_ADDED: "USER_ADDED",
  ADD_USER_FAILED: "ADD_USER_FAILED",
  GET_PRODUCTS: "GET_PRODUCTS",
  PRODUCTS_RECEIVED: "PRODUCTS_RECEIVED",
  GET_PRODUCTS_FAILED: "GET_PRODUCTS_FAILED",
  ADD_PRODUCT: "ADD_PRODUCT",
  PRODUCT_ADDED: "PRODUCT_ADDED",
  ADD_PRODUCT_FAILED: "ADD_PRODUCT_FAILED",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  PRODUCT_EDITED: "PRODUCT_EDITED",
  EDIT_PRODUCT_FAILED: "EDIT_PRODUCT_FAILED",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  PRODUCT_DELETED: "PRODUCT_DELETED",
  DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
};

export default actionTypes;
